name: 'Ubuntu'

on:
  workflow_dispatch:
    inputs:
      upload_game:
        type: boolean
        description: 'Upload game'
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build for Ubuntu'
    runs-on: ubuntu-latest
    env:
      GAME_PATH: ${{github.workspace}}/game
      OUTPUT: game_linux_${{github.run_number}}

    steps:
      - uses: actions/checkout@v4

      - name: 'Update packages'
        run: |
          sudo apt update
          sudo apt install ninja-build -y

      - name: 'Build'
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=${{ env.GAME_PATH }} -DCMAKE_BUILD_TYPE=Debug -G Ninja -S ${{github.workspace}} -B ${{github.workspace}}/cmake-build-debug
          cmake --build ${{github.workspace}}/cmake-build-debug --target game -j 6
          cmake --install ${{github.workspace}}/cmake-build-debug --config Debug

      - name: 'Create tarball'
        if: github.event.inputs.upload_game == 'true' || github.ref == 'refs/heads/main'
        run: |
          cd ${{ env.GAME_PATH }}
          ln -s ./bin/game ./game
          tar -cvf ${{github.workspace}}/${{ env.OUTPUT }}.tar *

      - name: 'Upload game'
        if: github.event.inputs.upload_game == 'true' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}.tar
