name: 'Windows'

on:
  workflow_dispatch:
    inputs:
      upload_game:
        type: boolean
        description: 'Upload game'
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build for Windows'
    runs-on: windows-latest
    env:
      SDL3_PATH: ${{github.workspace}}/SDL3
      GAME_PATH: ${{github.workspace}}/game
      OUTPUT: game_win64_${{github.run_number}}

    steps:
      - uses: actions/checkout@v3

      - name: 'Build SDL3'
        run: |
          git clone https://github.com/libsdl-org/SDL.git -b main
          cd SDL
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ env.SDL3_PATH }}
          cmake --build . --config Release -j 6
          cmake --install . --config Release

      - name: 'Build SDL3_image'
        run: |
          git clone https://github.com/libsdl-org/SDL_image.git -b main
          cd SDL_image
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=${{ env.SDL3_PATH }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ env.SDL3_PATH }}
          cmake --build . --config Release -j 6
          cmake --install . --config Release

      - name: 'Build'
        run: |
          cmake -DCMAKE_PREFIX_PATH="${{ env.SDL3_PATH }}" -DCMAKE_INSTALL_PREFIX=${{ env.GAME_PATH }} -DCMAKE_BUILD_TYPE=Debug -S ${{github.workspace}} -B ${{github.workspace}}/cmake-build-debug
          cmake --build ${{github.workspace}}/cmake-build-debug --target game -j 6
          cmake --install ${{github.workspace}}/cmake-build-debug --config Debug

      - name: 'Install 7zip'
        run: choco install 7zip.install

      - name: 'Install Mesa'
        shell: cmd
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
          "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          mklink opengl32.dll "x64\opengl32.dll"
          mklink libglapi.dll "x64\libglapi.dll"
        working-directory: ${{github.workspace}}/cmake-build-debug/Debug

      - name: 'Test'
        run: |
          cmake --build ${{github.workspace}}/cmake-build-debug --target game_test -j 6
          call "${{github.workspace}}/cmake-build-debug/Debug/game_test.exe"

      - name: 'Create shortcut'
        if: github.event.inputs.upload_game == 'true' || github.ref == 'refs/heads/main'
        run: |
          $WshShell = New-Object -comObject WScript.Shell
          $Shortcut = $WshShell.CreateShortcut("${{ env.GAME_PATH }}/game.lnk")
          $Shortcut.TargetPath = "${{ env.GAME_PATH }}/bin/game.exe"
          $Shortcut.IconLocation = "${{ env.GAME_PATH }}/bin/game.exe,0"
          $Shortcut.WorkingDirectory = "."
          $Shortcut.Save()

      - name: 'Upload game'
        if: github.event.inputs.upload_game == 'true' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.GAME_PATH }}/*
